name: Automatisation des tests
on: push
jobs:
  Compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Compilation
        run: |
          last_directory=$(basename ${{ runner.workspace }})
          git clone https://github.com/${{ github.repository }}.git
          cd ./$last_directory
          mkdir build
          cd build
          cmake ..
          make
          make test
  Test_Add:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Test fonction add
        run: |
          last_directory=$(basename ${{ runner.workspace }})
          git clone https://github.com/${{ github.repository }}.git
          cd ./$last_directory
          mkdir build
          cd build
          cmake ..
          make
          ./src/calculator add 10 5
   Test_Sub:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test fonction sub
        run: |
          cd build
          ./src/calculator sub 10 5
    Test_Mul:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test fonction mul
        run: |
          cd build
          ./src/calculator mul 10 5

  Test_Div:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test fonction div
        run: |
          cd build
          ./src/calculator div 10 5
